package com.ibm.lab;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Empregado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Matrícula do funcionário")
	private java.lang.String matricula;
	@org.kie.api.definition.type.Label(value = "Nome do funcionário")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label(value = "E-mail do funcionário")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Cargo do funcionário")
	private java.lang.String cargo;
	@org.kie.api.definition.type.Label(value = "Sálario mensal do funcionário")
	private double salario;

	public Empregado() {
	}

	public java.lang.String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(java.lang.String matricula) {
		this.matricula = matricula;
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getCargo() {
		return this.cargo;
	}

	public void setCargo(java.lang.String cargo) {
		this.cargo = cargo;
	}

	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

	public Empregado(java.lang.String matricula, java.lang.String nome,
			java.lang.String email, java.lang.String cargo, double salario) {
		this.matricula = matricula;
		this.nome = nome;
		this.email = email;
		this.cargo = cargo;
		this.salario = salario;
	}

}